### ISSUE TITLE
transport_read_layer error

### ISSUE THREAD

**Issue by sherwinkh** [neutrinolabs/NeutrinoRDP#20]
I encountered the error：
send: Connection reset by peer
transport_read_layer: unknown layer 3
transport_read: transport_read_layer failed
transport_check_fds: transport_read_nonblocking failed
Failed to check FreeRDP file descriptor
then, the NeutrinoRDP disconnect，someone can help?
###
int transport_read_layer(rdpTransport* transport, uint8* data, int bytes)
{
	int read = 0;
	int status = -1;

	LLOGLN(10, ("transport_read_layer:"));
	while (read < bytes)
	{
		switch (transport->layer)
		{
			case TRANSPORT_LAYER_TSG:
			case TRANSPORT_LAYER_TLS:
				status = tls_read(transport->tls_in, data + read, bytes - read);
				break;
			case TRANSPORT_LAYER_TCP:
				status = tcp_read(transport->tcp_in, data + read, bytes - read);
				break;
			//case TRANSPORT_LAYER_TSG:
				//status = tsg_read(transport->tsg, data + read, bytes - read);
				//break;
			default:
				LLOGLN(0, ("transport_read_layer: unknown layer %d", transport->layer));
				break;
		}

		/* blocking means that we can't continue until this is read
		   it's not tcp blocking */

		if (transport->blocking == false)
			return status;
...
###

**Comment by jsorg71** [comment]
@sherwinkh It looks to me like the other end is disconnecting you
